### ISSUE TITLE
Field labels are cut off at low resolutions

### ISSUE THREAD

**Issue by brian-slate** [purecloudlabs/json-schema-designer#15]
Item edit labels are cut off at low resolutions. Maybe we have the fields pop below instead?

![image](https://user-images.githubusercontent.com/799088/56823951-1737b800-680a-11e9-9959-abdd59edc1e3.png)

**Comment by pmoaddel** [comment]
![image](https://user-images.githubusercontent.com/11447714/79623784-bd4b9480-80e3-11ea-91cb-a9c1af631e34.png)
closing fixed.
